prompt = "> whoami"
name = "Lokesh Pawar"
designation = "Jr. R&D Engineer@Dozee"

[logo.gmail]
path = "assets/gmail.png"
username = "ilokeshpawar@gmail.com"
horizontal_offset = 50
vertical_offset = 238

[logo.github]
path = "assets/github.png"
username = "lokeshpawar"
horizontal_offset = 50
vertical_offset = 275

[logo.linkedin]
path = "assets/linkedin.png"
username = "lokesh-pawar-402096a1"
horizontal_offset = 50
vertical_offset = 310

[fonts]
path = "assets/fonts/NotoSansMono-VariableFont_wdth,wght.ttf"
